@startuml

interface ReprodutorMusical {
    +tocar()
    +pausar()
    +selecionarMusica(musica: String)
}

interface AparelhoTelefonico {
    +ligar(numero: String)
    +atender()
    +iniciarCorreioVoz()
}

interface NavegadorInternet {
    +exibirPagina(url: String)
    +adicionarNovaAba()
    +atualizarPagina()
}

class iPhone {
    +tocar()
    +pausar()
    +selecionarMusica(musica: String)
    +ligar(numero: String)
    +atender()
    +iniciarCorreioVoz()
    +exibirPagina(url: String)
    +adicionarNovaAba()
    +atualizarPagina()
}

ReprodutorMusical <|-- iPhone
AparelhoTelefonico <|-- iPhone
NavegadorInternet <|-- iPhone

@enduml
